############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About TKLaw"
url = "about/"
weight = 2

[[main]]
name = "Services"
url = "services/"
weight = 3

[[main]]
weight = 4
name = "Pages"
hasChildren = true

[[main]]
parent = "Pages"
name = "Blog"
url = "blog/"

[[main]]
parent = "Pages"
name = "Contact"
url = "contact/"

[[main]]
parent = "Pages"
name = "Authors"
url = "authors/"

[[main]]
parent = "Pages"
name = "Categories"
url = "categories/"

[[main]]
parent = "Pages"
name = "404 Page"
url = "404/"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Elements"
url = "elements/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3

############# Vietnamese navigation ##############

# # main menu
# [[main]]
# name = "Trang chủ"
# url = "/"
# weight = 1

# [[main]]
# name = "Giới thiệu"
# url = "about/"
# weight = 2

# [[main]]
# name = "Dịch vụ"
# url = "services/"
# weight = 3

# [[main]]
# weight = 4
# name = "Tư liệu"
# hasChildren = true

# [[main]]
# parent = "Pages"
# name = "Blog"
# url = "blog/"

# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "contact/"

# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "authors/"

# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "categories/"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "404/"


# # footer menu
# [[footer]]
# name = "Giới thiệu"
# url = "about/"
# weight = 1

# [[footer]]
# name = "Dịch vụ"
# url = "elements/"
# weight = 2

# [[footer]]
# name = "Chính sách riêng tư"
# url = "privacy-policy/"
# weight = 3
